modLoader="javafml"
loaderVersion="[8,)"
license="MIT"
[[mods]]
modId="espmod"
version="1.0"
displayName="ESP Mod"
description="Un mod simple pour afficher des boîtes autour des entités."
authors="VotreNom"